CT-2847 Make the "request info" as optional (#1106)
* CT-2847: make request_info optional

* Made the error of NoMethodError undefined method `dd' less possible to appear

* Removed the line related to request info

* Fixed the tests

* Changed the message when request info is empty

* Added test covering empty request for offender-sar

* Minor wording change

* simplied the test case based on feed back

* minor change to test spec

* minor wording change

Co-authored-by: vampireinsun <yikang.mao@yahoo.com>