CT-3987 upgrade rails 5 to rails 6 (#1824)
* CT-3987 upgrade rails 5 to rails 6

* Fixed the error of Failure/Error: ActiveRecord::Migration.maintain_test_schema!, ActiveRecord::ConnectionNotEstablished: connection is closed

* fixed the warning of "DEPRECATION WARNING: Initialization autoloaded the constants "

* fixed the warning of "DEPRECATION WARNING: config.active_support.use_sha1_digests is deprecated and will be removed from Rails 6.2"

* fixed the warning of "warning: control_d_handler's arity of 2 parameters was deprecated (eval_string, pry_instance)"

* Fixed the error of undefined method `add_as_source' for nil:NilClass

* fixed the error of "Deprecate update_attributes and update_attributes!"

* Fixed the faled test for http header of 'Content-Disposition' due to upgrade

* fixed the error of `it` is not available from within an example

* Fixed the remained and failed test specs

* fixed the warning of 'DEPRECATION WARNING: Calling `<<` to an ActiveModel::Errors message array in order to add an error is deprecated.'

* added :password into filter_parameters of application.config just in case